# Generated by Django 3.0.6 on 2021-06-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(max_length=255, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
