# Generated by Django 3.2.4 on 2021-06-14 17:31
import django.db.models.deletion
from django.db import migrations
from django.db import models

import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_auto_20210611_1544"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                max_length=255,
                null=True,
                upload_to="documents/",
                validators=[main_app.models.validate_file_extension],
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folder_files",
                to="main_app.folder",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="folders",
                to="main_app.folder",
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
